version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always

  main-controller:
    image: controller
    volumes:
      - ./main-controller:/main-controller
    depends_on:
      - redis0
      - redis1
    environment:
      REDIS0: redis0
      REDIS1: redis1

  redis0:
    image: 'bitnami/redis:latest'
    restart: always
    hostname: redis0.docker
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  worker0:
    image: worker
    depends_on:
      - redis0
    environment:
      REDIS: redis0
      CUDA_VISIBLE_DEVICES: 0
    volumes:
      - ./tf-worker:/tf-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis1:
    image: 'bitnami/redis:latest'
    restart: always
    hostname: redis1.docker
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  worker1:
    image: worker
    depends_on:
      - redis1
    environment:
      REDIS: redis1
      CUDA_VISIBLE_DEVICES: 1
    volumes:
      - ./tf-worker:/tf-worker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
